# Generated by Django 5.0 on 2023-12-14 11:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0003_remove_checkout_items'),
        ('item', '0005_cartitem_checkout'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='checkout',
        ),
        migrations.AddField(
            model_name='shoppingcart',
            name='checkout',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='checkout.checkout'),
        ),
    ]
