# Generated by Django 5.0 on 2023-12-14 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0006_remove_cartitem_checkout_shoppingcart_checkout'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shoppingcart',
            name='checkout',
        ),
    ]
