# Generated by Django 4.2.7 on 2023-12-13 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='address',
            options={'verbose_name_plural': 'Address'},
        ),
        migrations.RenameField(
            model_name='address',
            old_name='state',
            new_name='region',
        ),
    ]
