# Generated by Django 5.0 on 2023-12-14 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0002_alter_address_options_rename_state_address_region'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checkout',
            name='items',
        ),
    ]
