# Generated by Django 5.0 on 2023-12-14 18:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0003_remove_checkout_items'),
        ('item', '0007_remove_shoppingcart_checkout'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkout',
            name='shopping_cart',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='item.shoppingcart'),
        ),
    ]
